.TH "C:/Users/Gabriel/Documents/GitHub/PdM/PracticaTP/Drivers/API/inc/API_debounce.h" 3 "Sun Apr 10 2022" "PdM TP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Gabriel/Documents/GitHub/PdM/PracticaTP/Drivers/API/inc/API_debounce.h \- API debounce\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdebounceFSM_init\fP (void)"
.br
.RI "Initialize FSM\&. "
.ti -1c
.RI "void \fBdebounceFSM_update\fP (void)"
.br
.RI "Update FSM\&. "
.ti -1c
.RI "bool \fBreadKey\fP (void)"
.br
.RI "Read key\&. "
.in -1c
.SH "Detailed Description"
.PP 
API debounce\&. 


.PP
\fBAuthor\fP
.RS 4
Gabriel Postolov 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void debounceFSM_init (void)"

.PP
Initialize FSM\&. 
.PP
\fBParameters\fP
.RS 4
\fINone\&.\fP 
.RE
.PP
\fBReturn values\fP
.RS 4
\fINone\&.\fP 
.RE
.PP

.SS "void debounceFSM_update (void)"

.PP
Update FSM\&. 
.PP
\fBParameters\fP
.RS 4
\fINone\&.\fP 
.RE
.PP
\fBReturn values\fP
.RS 4
\fINone\&.\fP 
.RE
.PP

.SS "bool readKey (void)"

.PP
Read key\&. 
.PP
\fBParameters\fP
.RS 4
\fINone\&.\fP 
.RE
.PP
\fBReturn values\fP
.RS 4
\fItrue\fP Button User pressed\&. 
.br
\fIfalse\fP Button User not pressed\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for PdM TP from the source code\&.
