.TH "C:/Users/Gabriel/Documents/GitHub/PdM/PracticaTP/Drivers/API/src/API_uart.c" 3 "Sun Apr 10 2022" "PdM TP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Gabriel/Documents/GitHub/PdM/PracticaTP/Drivers/API/src/API_uart.c \- API uart\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br
\fC#include 'stm32f4xx_hal\&.h'\fP
.br
\fC#include 'stm32f4xx_nucleo_144\&.h'\fP
.br
\fC#include 'API_uart\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBuartinit\fP (void)"
.br
.RI "Initialize UART and send the configuration by UART\&. "
.ti -1c
.RI "void \fBuartsendString\fP (uint8_t *pstring)"
.br
.RI "Send a string by UART\&. "
.ti -1c
.RI "void \fBuartSendStringSize\fP (uint8_t *pstring, uint16_t size)"
.br
.RI "Send a part of string by UART\&. "
.ti -1c
.RI "void \fBuartReceiveStringSize\fP (uint8_t *pstring, uint16_t size)"
.br
.RI "Receive a string by UART\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "UART_HandleTypeDef \fBUartHandle\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
API uart\&. 


.PP
\fBAuthor\fP
.RS 4
Gabriel Postolov 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "bool uartinit (void)"

.PP
Initialize UART and send the configuration by UART\&. 
.PP
\fBParameters\fP
.RS 4
\fINone\&.\fP 
.RE
.PP
\fBReturn values\fP
.RS 4
\fItrue\fP UART initialized successfully\&. 
.br
\fIfalse\fP UART was not initialized successfully\&. 
.RE
.PP

.SS "void uartReceiveStringSize (uint8_t * pstring, uint16_t size)"

.PP
Receive a string by UART\&. 
.PP
\fBParameters\fP
.RS 4
\fIpstring\fP String to be received\&. 
.br
\fIsize\fP Number of characters to receive\&. 
.RE
.PP
\fBReturn values\fP
.RS 4
\fINone\&.\fP 
.RE
.PP

.SS "void uartsendString (uint8_t * pstring)"

.PP
Send a string by UART\&. 
.PP
\fBParameters\fP
.RS 4
\fIpstring\fP String to be sent\&. 
.RE
.PP
\fBReturn values\fP
.RS 4
\fINone\&.\fP 
.RE
.PP

.SS "void uartSendStringSize (uint8_t * pstring, uint16_t size)"

.PP
Send a part of string by UART\&. 
.PP
\fBParameters\fP
.RS 4
\fIpstring\fP String to be sent\&. 
.br
\fIsize\fP size of the string to be sent\&. 
.RE
.PP
\fBReturn values\fP
.RS 4
\fINone\&.\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for PdM TP from the source code\&.
