.TH "delay_t" 3 "Sun Apr 10 2022" "PdM TP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
delay_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "tick_t \fBstartTime\fP"
.br
.ti -1c
.RI "tick_t \fBduration\fP"
.br
.ti -1c
.RI "bool_t \fBrunning\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for PdM TP from the source code\&.
